inputs:
  - path: ./photos
    include: ["**/*.png", "**/*.jpg", "**/*.jpeg"]
    watch: false

pipeline:
  - node: decode
  - node: resize
    when: image
    params:
      width: 2048
      height: auto
      scaler: lanczos3
  - node: encode
    when: image
    params:
      codec: webp
      quality: 80

outputs:
  - path: ./web-ready
    container: file
    pattern: "{base}.webp"
