inputs:
  - path: ./inbox
    include: ["**/*.mp4", "**/*.mov"]
    watch: false

pipeline:
  - node: decode
  - node: scale
    when: video
    params:
      width: 1920
      height: 1080
      scaler: lanczos
  - node: bitrate
    when: video
    params:
      mode: vbr
      target: 4500k
  - node: encode
    when: video
    params:
      codec: h264
      preset: p5
      hwaccel: auto
  - node: encode
    when: audio
    params:
      codec: aac
      bitrate: 192k

outputs:
  - path: ./out
    container: mp4
    pattern: "{base}_{width}x{height}.{ext}"

on_error:
  strategy: continue
  move_to: ./errors
